# Generated by Django 4.2 on 2024-05-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240428_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagine_filter',
            new_name='image_filter',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_rgq6aq', upload_to='images/'),
        ),
    ]
